name: 'Main'

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  test:
    name: 'Main'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42
      with:
        dir_names: true
        files: 'src/**'
        files_ignore: 'src/environment1/*/*.hcl'
        dir_names_max_depth: 4


    - name: Run step if more than one directory in src/ have been changed
      if: ${{ steps.changed-files.outputs.all_changed_files_count > 1 }}
      run: |
        echo "There are changes in more than one directory in src/ :"
        echo ${{ steps.changed-files.outputs.all_changed_files }} | tr ' ' '\n'
        echo "Please, make changes in one directory at a time."
        exit 1

    - name: Run step if one directory in src/ has been changed
      if: ${{ steps.changed-files.outputs.all_changed_files_count == 1 }}
      run: |
        echo "Changes detected in ${{ steps.changed-files.outputs.all_changed_files }}"
    
    - name: Run step if no file(s) in src/ have been changed
      if: ${{ steps.changed-files.outputs.all_changed_files_count == 0 }}
      run: |
        echo "No files in src/ have been changed."